<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bank
[


<!--This document models on bank, and can handle many branches(at least one)-->
<!ELEMENT Bank (branch+)>
<!ATTLIST Bank branch CDATA #FIXED "ICICI Bank">
<!--A Branch has branch data, customers and at least one employee and atm-->
<!ELEMENT branch (branch_data, customer*, employee+, atm+,cheque_deposit_machine*,cash_deposit_machine*,passbook_printer*)>
<!--Branch data of a bank includes name and its address-->
<!ELEMENT branch_data (address, name?)>
<!ELEMENT address (#PCDATA)>
<!--A customer has some personal data, at least one account and it can have any number of loan-->
<!ELEMENT customer (personal_data, account+, loan*)>
<!ATTLIST customer customer_id ID #REQUIRED>
<!ATTLIST customer customer_since_years CDATA "0">
<!--The personal data of a person has name, address and DOB-->
<!ELEMENT personal_data (name, date_of_birth, address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT date_of_birth (#PCDATA)>
<!--An account is identified by account number, and contains it's balance as well as transactions-->
<!ELEMENT account (balance, transactions*)>
<!--Most account are basic accounts, that can be accessed any time, however an account could also be a saving accounts-->
<!ATTLIST account account_type (saving_account|basic_account) "basic_account">
<!ATTLIST account account_no ID #REQUIRED>
<!ELEMENT balance (#PCDATA)>
<!--A transaction can be transfer from one account to another, deposit or withdrawal, and every transaction is done on a date-->
<!ELEMENT transactions (date, (transfer|withdraw|deposit))>
<!ELEMENT date (#PCDATA)>
<!ELEMENT deposit (amount)>
<!ELEMENT withdraw (amount)>
<!--The transfer contain amount and account_no of involved account-->
<!ELEMENT transfer (amount)>
<!ATTLIST transfer from IDREF #REQUIRED>
<!ATTLIST transfer to IDREF #REQUIRED>
<!--A loan is identified by  ID, has an amount, interest rate and maximum duration-->
<!ELEMENT loan (amount)>
<!--There exist different type of loans, to group loans with similar conditions-->
<!--A loan can be of different types like vehicle,real estate etc-->
<!ATTLIST loan loan_type (vehicle_loan|real_estate_loan|agricultural_loan|education_loan|personal_loan) #IMPLIED>
<!ATTLIST loan max_duration CDATA #IMPLIED>
<!ATTLIST loan loan_number ID #REQUIRED>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT interest (#PCDATA)>
<!--Each ATM is filled with money, can be specified using it's individual ID and saves the days until the next routine check-->
<!ELEMENT atm (#PCDATA)>
<!ATTLIST atm atm_id ID #REQUIRED>
<!ATTLIST atm days_to_maintainance CDATA "60">
<!--An employee is described by his personal data, salary, job and an  ID-->
<!ELEMENT employee (personal_data, (manager|customer_care|customer_support|technician))>
<!ATTLIST employee employee_id ID #REQUIRED>
<!ATTLIST employee salary CDATA #IMPLIED>
<!ELEMENT manager EMPTY>
<!ATTLIST manager subordinates IDREFS #REQUIRED>
<!ELEMENT customer_care EMPTY>
<!ATTLIST customer_care responsible_for IDREFS #REQUIRED>
<!ELEMENT customer_support EMPTY>
<!ATTLIST customer_support responsible_for IDREFS #REQUIRED>
<!ELEMENT technician EMPTY>
<!ATTLIST technician maintains IDREFS #REQUIRED>


]>
<Bank branch="ICICI Bank">
	<branch>
		<branch_data>
			<address>
				Chennai,India
			</address>
			<name>
				ICICI Central Bank
			</name>
		</branch_data>
		<customer customer_id="cust1" customer_since_years="1">
			<personal_data>
				<name>Shivam_Kumar </name>
				<date_of_birth>1998-03-24</date_of_birth>
				<address>East Champaran,Bihar</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc1">
				<balance>5000000000</balance>
				<transactions>
					<date>2021-02-01</date>
					<withdraw>
						<amount>60000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2021-02-02</date>
					<deposit>
						<amount>70000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2021-02-03</date>
					<deposit>
						<amount>25000</amount>
					</deposit>
				</transactions>
			</account>
			<loan loan_type="agricultural_loan" max_duration="2" loan_number="lo1">
				<amount> 50000 </amount>
				<interest > 2 </interest >
			</loan>
		</customer>
		<customer customer_id="cust2" customer_since_years="4">
			<personal_data>
				<name>Ruhal_Kumar </name>
				<date_of_birth>1997-07-04</date_of_birth>
				<address>Muzaffarpur ,Bihar</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc2">
				<balance>100000000</balance>
				<transactions>
					<date>2021-02-01</date>
					<withdraw>
						<amount>6000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2021-03-02</date>
					<deposit>
						<amount>760000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2021-04-03</date>
					<deposit>
						<amount>30000</amount>
					</deposit>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust3" customer_since_years="3">
			<personal_data>
				<name>Amit_Kumar_Singh </name>
				<date_of_birth>1995-03-24</date_of_birth>
				<address>West  Champaran,Bihar</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc3">
				<balance>5000000000</balance>
				<transactions>
					<date>2022-02-01</date>
					<withdraw>
						<amount>670000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2022-02-02</date>
					<deposit>
						<amount>79000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2022-02-03</date>
					<deposit>
						<amount>25000</amount>
					</deposit>
				</transactions>
			</account>
			<loan loan_type="agricultural_loan" max_duration="2" loan_number="lo2">
				<amount> 50000 </amount>
				<interest > 2 </interest >
			</loan>
		</customer>
		<customer customer_id="cust4" customer_since_years="6">
			<personal_data>
				<name>Sumit_Kumar_Singh </name>
				<date_of_birth>1999-07-24</date_of_birth>
				<address>Samastipur ,Bihar</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc4">
				<balance>5006740000</balance>
				<transactions>
					<date>2021-07-01</date>
					<withdraw>
						<amount>60700</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2021-08-02</date>
					<deposit>
						<amount>706700</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2021-09-03</date>
					<deposit>
						<amount>205000</amount>
					</deposit>
				</transactions>
			</account>
			<loan loan_type="agricultural_loan" max_duration="2" loan_number="lo3">
				<amount> 50000 </amount>
				<interest > 2 </interest >
			</loan>
		</customer>
		<customer customer_id="cust5" customer_since_years="5">
			<personal_data>
				<name>Shivangi_Tripathi </name>
				<date_of_birth>1998-05-27</date_of_birth>
				<address>Lucknow ,U.P</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc5">
				<balance>50876000000</balance>
				<transactions>
					<date>2021-03-01</date>
					<withdraw>
						<amount>606000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2021-03-02</date>
					<deposit>
						<amount>700900</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2021-03-03</date>
					<deposit>
						<amount>25010</amount>
					</deposit>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust6" customer_since_years="6">
			<personal_data>
				<name>Kamal_Hassan_H </name>
				<date_of_birth>1988-03-09</date_of_birth>
				<address>Chennai, Tamilnadu</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc6">
				<balance>7000000</balance>
				<transactions>
					<date>2020-12-12</date>
					<withdraw>
						<amount>50000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2021-01-14</date>
					<deposit>
						<amount>900000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2021-04-23</date>
					<withdraw>
						<amount>15000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust7" customer_since_years="4">
			<personal_data>
				<name>Surya_S </name>
				<date_of_birth>1995-09-29</date_of_birth>
				<address>Trichy, Tamilnadu</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc7">
				<balance>2435600</balance>
				<transactions>
					<date>2019-05-06</date>
					<withdraw>
						<amount>50000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2019-12-11</date>
					<deposit>
						<amount>23500</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-11-30</date>
					<withdraw>
						<amount>12000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2021-01-03</date>
					<withdraw>
						<amount>14000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust8" customer_since_years="6">
			<personal_data>
				<name>Rajan_K </name>
				<date_of_birth>1995-09-29</date_of_birth>
				<address>Vellore, Tamilnadu</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc8">
				<balance>64500</balance>
				<transactions>
					<date>2018-11-16</date>
					<deposit>
						<amount>23500</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2019-12-11</date>
					<deposit>
						<amount>500</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-03-30</date>
					<withdraw>
						<amount>3460</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2021-11-03</date>
					<deposit>
						<amount>12500</amount>
					</deposit>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust9" customer_since_years="10">
			<personal_data>
				<name>Ramesh_A </name>
				<date_of_birth>1975-02-11</date_of_birth>
				<address>Vellore, Tamilnadu</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc9">
				<balance>120000</balance>
				<transactions>
					<date>2018-01.16</date>
					<withdraw>
						<amount>14000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2019-02-01</date>
					<withdraw>
						<amount>3400</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2019-03-02</date>
					<deposit>
						<amount>13000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-22</date>
					<deposit>
						<amount>10500</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-13</date>
					<deposit>
						<amount>1500</amount>
					</deposit>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust10" customer_since_years="03">
			<personal_data>
				<name>Karthik_S </name>
				<date_of_birth>1999-08-11</date_of_birth>
				<address>Chennai, Tamilnadu</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc10">
				<balance>220000</balance>
				<transactions>
					<date>2019-11.11</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-05-11</date>
					<withdraw>
						<amount>1000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-21</date>
					<deposit>
						<amount>3000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-22</date>
					<deposit>
						<amount>500</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-13</date>
					<withdraw>
						<amount>1000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust11" customer_since_years="03">
			<personal_data>
				<name>Deepansh_Raj </name>
				<date_of_birth>1998-06-17</date_of_birth>
				<address>Gorakhpur, Uttar Pradesh</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc11">
				<balance>230000</balance>
				<transactions>
					<date>2019-11-12</date>
					<withdraw>
						<amount>5000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-05-12</date>
					<withdraw>
						<amount>2000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-22</date>
					<deposit>
						<amount>4000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-23</date>
					<deposit>
						<amount>600</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-14</date>
					<withdraw>
						<amount>1000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust12" customer_since_years="03">
			<personal_data>
				<name>Rishabh_Sharma </name>
				<date_of_birth>1998-06-18</date_of_birth>
				<address>Pune, Maharashtra</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc12">
				<balance>240000</balance>
				<transactions>
					<date>2019-11-13</date>
					<withdraw>
						<amount>6000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-05-13</date>
					<withdraw>
						<amount>3000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-23</date>
					<deposit>
						<amount>5000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-24</date>
					<deposit>
						<amount>700</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-15</date>
					<withdraw>
						<amount>2000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust13" customer_since_years="03">
			<personal_data>
				<name>Siddhartha_Shukla </name>
				<date_of_birth>1998-06-19</date_of_birth>
				<address>Gorakhpur, Uttar Pradesh</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc13">
				<balance>250000</balance>
				<transactions>
					<date>2019-11-14</date>
					<withdraw>
						<amount>7000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-05-14</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-24</date>
					<deposit>
						<amount>6000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-25</date>
					<deposit>
						<amount>800</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-16</date>
					<withdraw>
						<amount>3000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust14" customer_since_years="03">
			<personal_data>
				<name>Shashank_Tripathi </name>
				<date_of_birth>1998-07-19</date_of_birth>
				<address>Noida, Uttar Pradesh</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc14">
				<balance>260000</balance>
				<transactions>
					<date>2019-11-15</date>
					<withdraw>
						<amount>8000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-05-15</date>
					<withdraw>
						<amount>5000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-25</date>
					<deposit>
						<amount>7000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-26</date>
					<deposit>
						<amount>900</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-17</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust15" customer_since_years="03">
			<personal_data>
				<name>Vishvendra_Tripathi </name>
				<date_of_birth>1998-07-19</date_of_birth>
				<address>Indore, Madhya Pradesh</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc15">
				<balance>270000</balance>
				<transactions>
					<date>2019-11-16</date>
					<withdraw>
						<amount>8000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-05-15</date>
					<withdraw>
						<amount>5000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-25</date>
					<deposit>
						<amount>7000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-26</date>
					<deposit>
						<amount>900</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-17</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust16" customer_since_years="03">
			<personal_data>
				<name>Apratim_Shivansh </name>
				<date_of_birth>1998-08-20</date_of_birth>
				<address>Kanpur, Uttar Pradesh</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc16">
				<balance>300000</balance>
				<transactions>
					<date>2019-10-16</date>
					<withdraw>
						<amount>8000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-06-15</date>
					<withdraw>
						<amount>5000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-25</date>
					<deposit>
						<amount>7000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-26</date>
					<deposit>
						<amount>900</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-17</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust17" customer_since_years="03">
			<personal_data>
				<name>Ankit_Aahil </name>
				<date_of_birth>1998-05-22</date_of_birth>
				<address>Shivan, Bihar</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc17">
				<balance>310000</balance>
				<transactions>
					<date>2019-10-16</date>
					<withdraw>
						<amount>8000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-06-15</date>
					<withdraw>
						<amount>5000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-25</date>
					<deposit>
						<amount>7000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-26</date>
					<deposit>
						<amount>900</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-17</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust18" customer_since_years="03">
			<personal_data>
				<name>Kush_Jalal </name>
				<date_of_birth>1985-12-10</date_of_birth>
				<address>Ahmedabad, Gujrat</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc18">
				<balance>210000</balance>
				<transactions>
					<date>2019-10-16</date>
					<withdraw>
						<amount>8000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-06-15</date>
					<withdraw>
						<amount>5000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-25</date>
					<deposit>
						<amount>7000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-26</date>
					<deposit>
						<amount>900</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-17</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust19" customer_since_years="03">
			<personal_data>
				<name>Ronak_Nahata </name>
				<date_of_birth>1998-04-22</date_of_birth>
				<address>Ahmedabad, Gujrat</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc19">
				<balance>210000</balance>
				<transactions>
					<date>2019-10-16</date>
					<withdraw>
						<amount>8000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-06-15</date>
					<withdraw>
						<amount>5000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-11-25</date>
					<deposit>
						<amount>7000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-01-26</date>
					<deposit>
						<amount>900</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-02-17</date>
					<withdraw>
						<amount>4000</amount>
					</withdraw>
				</transactions>
			</account>
		</customer>
		<customer customer_id="cust20" customer_since_years="02">
			<personal_data>
				<name>Shailesh_Kumar </name>
				<date_of_birth>1985-12-10</date_of_birth>
				<address>Salt Lake</address>
			</personal_data>
			<account account_type="basic_account" account_no="acc20">
				<balance>400000</balance>
				<transactions>
					<date>2020-02-10</date>
					<withdraw>
						<amount>3000</amount>
					</withdraw>
				</transactions>
				<transactions>
					<date>2020-03-20</date>
					<deposit>
						<amount>1000</amount>
					</deposit>
				</transactions>
				<transactions>
					<date>2020-03-30</date>
					<deposit>
						<amount>10000</amount>
					</deposit>
				</transactions>
			</account>
		</customer>
		<employee employee_id="emp1" salary="1000000">
			<personal_data>
				<name>Elon_Musk </name>
				<date_of_birth>1971-01-04</date_of_birth>
				<address>USA</address>
			</personal_data>
			<manager subordinates="emp2 emp3 emp4 emp5"></manager>
		</employee>
		<employee employee_id="emp2" salary="7500000">
			<personal_data>
				<name>Cristiano_Amon </name>
				<date_of_birth>1970-06-21</date_of_birth>
				<address>San Diego</address>
			</personal_data>
			<customer_care responsible_for="cust3 cust4"></customer_care>
		</employee>
		<employee employee_id="emp3" salary="2000000">
			<personal_data>
				<name>Gopal_Vittal </name>
				<date_of_birth>1967-11-01</date_of_birth>
				<address>Delhi</address>
			</personal_data>
			<customer_care responsible_for="cust1 cust2 cust5"></customer_care>
		</employee>
		<employee employee_id="emp4" salary="4000000">
			<personal_data>
				<name>Patrick_P._Gelsinger </name>
				<date_of_birth>1961-03-05</date_of_birth>
				<address>Silicon Valley</address>
			</personal_data>
			<technician maintains="ATM1 ATM2"></technician>
		</employee>
		<employee employee_id="emp5" salary="5000000">
			<personal_data>
				<name>Larry_Page </name>
				<date_of_birth>1979-07-05</date_of_birth>
				<address>USA</address>
			</personal_data>
			<technician maintains="ATM3 ATM4 ATM5"></technician>
		</employee>
		<employee employee_id="emp6" salary="15000000">
			<personal_data>
				<name>Sundar_Pichai </name>
				<date_of_birth>1975-03-15</date_of_birth>
				<address>Chennai</address>
			</personal_data>
			<manager subordinates="emp1 emp6 emp7 emp8"></manager>
		</employee>
		<employee employee_id="emp7" salary="5000000">
			<personal_data>
				<name>George_Bush </name>
				<date_of_birth>1960-07-13</date_of_birth>
				<address>USA</address>
			</personal_data>
			<customer_support responsible_for="cust6 cust7 cust8 cust9 cust10 cust11 cust12 cust13"></customer_support>
		</employee>
		<employee employee_id="emp8" salary="3000000">
			<personal_data>
				<name>Sergey_Brin </name>
				<date_of_birth>1977-07-02</date_of_birth>
				<address>USA</address>
			</personal_data>
			<customer_care responsible_for="cust6 cust7 cust8 cust9 cust10 cust11 cust12 cust13"></customer_care>
		</employee>
		<atm atm_id="ATM1" days_to_maintainance="10">50000</atm>
		<atm atm_id="ATM2" days_to_maintainance="11">75000</atm>
		<atm atm_id="ATM3" days_to_maintainance="12">25000</atm>
		<atm atm_id="ATM4" days_to_maintainance="13">20000</atm>
		<atm atm_id="ATM5" days_to_maintainance="14">35000</atm>
		<atm atm_id="ATM6" days_to_maintainance="15">50000</atm>
		<atm atm_id="ATM7" days_to_maintainance="17">30000</atm>
	</branch>
</Bank>

